repos:
  - repo: local
    hooks:
      - id: lint
        name: ESLint
        entry: bash -c 'cd apps/web && bun run lint'
        language: system
        files: \.(js|jsx|ts|tsx)$
        pass_filenames: false
      
      - id: format
        name: Prettier Format
        entry: bash -c 'cd apps/web && bun run format'
        language: system
        files: \.(js|jsx|ts|tsx|json|yaml|yml|md|mdx)$
        pass_filenames: false

      - id: format-check
        name: Prettier Format Check
        entry: bash -c 'cd apps/web && bun run format:check'
        language: system
        files: \.(js|jsx|ts|tsx|json|yaml|yml|md|mdx)$
        pass_filenames: false

      - id: type-check
        name: TypeScript Type Check
        entry: bash -c 'cd apps/web && bun run type-check'
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false