// @ts-nocheck -- skip type checking
import * as docs_13 from "../content/docs/stat/index.mdx?collection=docs&hash=1734788237133"
import * as docs_12 from "../content/docs/rl/q_learning.mdx?collection=docs&hash=1734788237133"
import * as docs_11 from "../content/docs/rl/mdp.mdx?collection=docs&hash=1734788237133"
import * as docs_10 from "../content/docs/rl/index.mdx?collection=docs&hash=1734788237133"
import * as docs_9 from "../content/docs/nlp/word_embeddings.mdx?collection=docs&hash=1734788237133"
import * as docs_8 from "../content/docs/nlp/tokenization.mdx?collection=docs&hash=1734788237133"
import * as docs_7 from "../content/docs/nlp/n_gram_models.mdx?collection=docs&hash=1734788237133"
import * as docs_6 from "../content/docs/nlp/index.mdx?collection=docs&hash=1734788237133"
import * as docs_5 from "../content/docs/ml/naive_bayes.mdx?collection=docs&hash=1734788237133"
import * as docs_4 from "../content/docs/ml/knn.mdx?collection=docs&hash=1734788237133"
import * as docs_3 from "../content/docs/ml/kmeans.mdx?collection=docs&hash=1734788237133"
import * as docs_2 from "../content/docs/ml/index.mdx?collection=docs&hash=1734788237133"
import * as docs_1 from "../content/docs/llm/index.mdx?collection=docs&hash=1734788237133"
import * as docs_0 from "../content/docs/dl/index.mdx?collection=docs&hash=1734788237133"
import * as blog_0 from "../content/blog/hello.mdx?collection=blog&hash=1734788237133"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const blog = _runtime.doc<typeof _source.blog>([{ info: {"path":"hello.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/blog/hello.mdx"}, data: blog_0 }]);
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"dl/index.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/dl/index.mdx"}, data: docs_0 }, { info: {"path":"llm/index.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/llm/index.mdx"}, data: docs_1 }, { info: {"path":"ml/index.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/ml/index.mdx"}, data: docs_2 }, { info: {"path":"ml/kmeans.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/ml/kmeans.mdx"}, data: docs_3 }, { info: {"path":"ml/knn.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/ml/knn.mdx"}, data: docs_4 }, { info: {"path":"ml/naive_bayes.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/ml/naive_bayes.mdx"}, data: docs_5 }, { info: {"path":"nlp/index.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/nlp/index.mdx"}, data: docs_6 }, { info: {"path":"nlp/n_gram_models.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/nlp/n_gram_models.mdx"}, data: docs_7 }, { info: {"path":"nlp/tokenization.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/nlp/tokenization.mdx"}, data: docs_8 }, { info: {"path":"nlp/word_embeddings.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/nlp/word_embeddings.mdx"}, data: docs_9 }, { info: {"path":"rl/index.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/rl/index.mdx"}, data: docs_10 }, { info: {"path":"rl/mdp.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/rl/mdp.mdx"}, data: docs_11 }, { info: {"path":"rl/q_learning.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/rl/q_learning.mdx"}, data: docs_12 }, { info: {"path":"stat/index.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/stat/index.mdx"}, data: docs_13 }]);
export const meta = _runtime.meta<typeof _source.meta>([{ info: {"path":"meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/meta.json"}, data: {"pages":["stat","ml","dl","nlp","llm","rl"]} }, { info: {"path":"llm/meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/llm/meta.json"}, data: {"title":"LLM","root":true,"icon":"Bot"} }, { info: {"path":"dl/meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/dl/meta.json"}, data: {"title":"DL","root":true,"icon":"BrainCircuit"} }, { info: {"path":"ml/meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/ml/meta.json"}, data: {"title":"ML","pages":["---Guide---","index","---Clustering---","kmeans","---Classification---","knn","naive_bayes"],"root":true,"defaultOpen":true,"icon":"Pencil"} }, { info: {"path":"nlp/meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/nlp/meta.json"}, data: {"title":"NLP","pages":["---Guide---","index","---Text Processing---","tokenization","---Language Models---","word_embeddings","n_gram_models"],"root":true,"defaultOpen":true,"icon":"MessageSquare"} }, { info: {"path":"stat/meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/stat/meta.json"}, data: {"title":"Stat","root":true,"icon":"Sigma"} }, { info: {"path":"rl/meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/rl/meta.json"}, data: {"title":"RL","pages":["---Guide---","index","---Foundational Concepts---","mdp","---Classic Algorithms---","q_learning"],"root":true,"defaultOpen":true,"icon":"Gamepad2"} }]);