// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/stat/index.mdx?collection=docs&hash=1734788237133"
import * as docs_5 from "../content/docs/ml/naive_bayes.mdx?collection=docs&hash=1734788237133"
import * as docs_4 from "../content/docs/ml/knn.mdx?collection=docs&hash=1734788237133"
import * as docs_3 from "../content/docs/ml/kmeans.mdx?collection=docs&hash=1734788237133"
import * as docs_2 from "../content/docs/ml/index.mdx?collection=docs&hash=1734788237133"
import * as docs_1 from "../content/docs/llm/index.mdx?collection=docs&hash=1734788237133"
import * as docs_0 from "../content/docs/dl/index.mdx?collection=docs&hash=1734788237133"
import * as blog_0 from "../content/blog/hello.mdx?collection=blog&hash=1734788237133"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const blog = _runtime.doc<typeof _source.blog>([{ info: {"path":"hello.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/blog/hello.mdx"}, data: blog_0 }]);
export const docs = _runtime.doc<typeof _source.docs>([{ info: {"path":"dl/index.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/dl/index.mdx"}, data: docs_0 }, { info: {"path":"llm/index.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/llm/index.mdx"}, data: docs_1 }, { info: {"path":"ml/index.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/ml/index.mdx"}, data: docs_2 }, { info: {"path":"ml/kmeans.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/ml/kmeans.mdx"}, data: docs_3 }, { info: {"path":"ml/knn.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/ml/knn.mdx"}, data: docs_4 }, { info: {"path":"ml/naive_bayes.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/ml/naive_bayes.mdx"}, data: docs_5 }, { info: {"path":"stat/index.mdx","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/stat/index.mdx"}, data: docs_6 }]);
export const meta = _runtime.meta<typeof _source.meta>([{ info: {"path":"meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/meta.json"}, data: {"pages":["stat","ml","dl","llm"]} }, { info: {"path":"llm/meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/llm/meta.json"}, data: {"title":"LLM","root":true,"icon":"Bot"} }, { info: {"path":"dl/meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/dl/meta.json"}, data: {"title":"DL","root":true,"icon":"BrainCircuit"} }, { info: {"path":"ml/meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/ml/meta.json"}, data: {"title":"ML","pages":["---Guide---","index","---Clustering---","kmeans","---Classification---","knn","naive_bayes"],"root":true,"defaultOpen":true,"icon":"Pencil"} }, { info: {"path":"stat/meta.json","absolutePath":"/home/mathewshen/Workspace/Projects/github/website/apps/web/content/docs/stat/meta.json"}, data: {"title":"Stat","root":true,"icon":"Sigma"} }]);