name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd apps/web && bun install

      - name: Type check
        run: cd apps/web && bun run type-check

      - name: Lint
        run: cd apps/web && bun run lint

      - name: Format check
        run: cd apps/web && bun run format:check

  build:
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd apps/web && bun install

      - name: Build
        run: cd apps/web && bun run build
